### ISSUE TITLE
Diesel as an option

### ISSUE THREAD

**Issue by lilianmoraru** [hjr3/webservice-demo-rs#2]
I do not use Twitter so, I have the impression this is the only way to write this :)

I saw that you use PostgreSQL and in case that you didn't know about Diesel, I wanted to make you aware that there is a very nice ORM library for Rust: http://diesel.rs/ / https://github.com/diesel-rs/diesel
Makes these things simpler and more beautiful to write, with some erroneous queries prevention.

**Comment by hjr3** [comment]
Hi @lilianmoraru,

I think Diesel is a good choice. I spoke briefly about using Diesel in the future [on r/rust](https://www.reddit.com/r/rust/comments/4kqetv/connecting_a_webservice_to_a_database_in_rust/d3hp5e3?context=1).

**Comment by lilianmoraru** [comment]
Ok, so you are already aware of this library, nice, closing.
